### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by angikama** [angikama/hangman#1]
- Even though the number of lives is set to 5, the game does not end and show the end message when the lives equal 0, the lives go into the negative numbers
- When all the letters are guessed, the game does not end and show the congratulations message
- When a letter is guessed that appears multiple times in the word, all instances of the letter are not replaced at the same time

**Comment by IvanYingX** [comment]
Hey @angikama , great way to ask for support!

Your code looks nice and clean, but there is one thing you are missing in the `while` loop

You have a `while True` loop, so it won't stop until you tell it to do so. What is the keyword for `break`ing out of a loop?

**Comment by angikama** [comment]
'break' after the winning and losing message?

**Comment by angikama** [comment]
@IvanYingX 

I missed out 'break' after the winning and losing messages. The game now ends! Thank you for the prompt.

Only thing that remains is the issue involving words with multiple of the same letter, I'll think a little more about it though.
